# Generated by Django 2.2.1 on 2019-11-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190908_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img_id',
            field=models.IntegerField(default='1'),
        ),
    ]
