# Generated by Django 2.2.1 on 2019-12-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20191201_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalamount',
            name='num',
        ),
        migrations.RemoveField(
            model_name='totalamount',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='totalamount',
            name='total_step',
        ),
        migrations.AddField(
            model_name='totalamount',
            name='portfolio_id',
            field=models.IntegerField(default='0'),
        ),
    ]
