# Generated by Django 2.2.1 on 2019-12-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20191201_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='totalAmount',
            new_name='portfolioKey',
        ),
    ]
