# Generated by Django 2.2.1 on 2019-12-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_nowdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nowDate',
        ),
    ]
